spring:
  application:
    name: smartContest

  datasource:
    url: jdbc:mysql://localhost:3306/smart_contest
    username: root
    password: NewPassword123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false


judge0:
  base-url: https://ce.judge0.com

judge:
  workers: 4
  queue-capacity: 1000
  poll-delay-ms: 1000
  poll-timeout-ms: 30000